# Criando docker-compose para o bot de compras

# Este arquivo docker-compose.yml define os serviços necessários para rodar o bot de compras.
# Ele inclui a construção da imagem do bot, configuração de variáveis de ambiente e volumes.

# versão do docker-compose
version: "3.8"

# serviços que serão executados
services:
  # Nome do serviço
  bot-compras:
    # Build da imagem
    build: .
    # imagem para subir no dockerhub (usuario/nome-da-imagem:tag)
    image: ${USER_DOCKERHUB}/bot-compras:latest
    # Nome do container
    container_name: bot-compras
    # Reinicia o container automaticamente em caso de falha
    restart: always
    # Arquivo .env
    env_file: .env
    # Configuração de logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m" # Tamanho máximo do arquivo de log - 10MB
        max-file: "3" # Mantém os 3 últimos arquivos de log
    # Volumes para persistência de dados
    volumes:
      - ./products.db:/app/products.db
      - ./debug.log:/app/debug.log

    # Comando para rodar o bot
    command: ["python", "-u", "bot_app.py"]
